### ISSUE TITLE
Concourse Metadata doesn't work

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [burdzwastaken/concourse-spinnaker-resource#7]
Using the example pipeline
```
jobs:
- name: trigger-pipeline
  plan:
  - put: spinnaker
    params:
      spinnaker_application: samplespinnakerapp
      spinnaker_pipeline: samplespinnakerapp
      trigger_params:
        build_id: (build ${BUILD_ID})
```

This shows up in un-interpolated Spinnaker as;
```
build_id: "(build ${BUILD_ID})"
```

**Comment by xtreme-sameer-vohra** [comment]
Using the example pipeline
```
jobs:
- name: trigger-pipeline
  plan:
  - put: spinnaker
    params:
      spinnaker_application: samplespinnakerapp
      spinnaker_pipeline: samplespinnakerapp
      trigger_params:
        build_id: (build ${BUILD_ID})
```

This shows up in un-interpolated Spinnaker as;
```
build_id: "(build ${BUILD_ID})"
```
